<?php

namespace autoEcoleBundle\Repository;

/**
 * EntrainementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrainementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return integer
     * @throws \Doctrine\DBAL\DBALException
     */
    public function countAll(){
        $em = $this->getEntityManager();
        $sql = "SELECT COUNT(*) as number FROM entrainement WHERE dateDebut > NOW()";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll()[0]['number'];
    }

    public function revenus(){
        $em = $this->getEntityManager();
        $sql = "SELECT SUM(v.prix*e.nombreHeure) as revenus FROM entrainement e INNER JOIN voiture v on e.voiture = v.id 
                  WHERE e.dateDebut < NOW()";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll()[0]['revenus'];
    }
}
