<?php

namespace autoEcoleBundle\Repository;
use PDO;

/**
 * MoniteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoniteurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return integer
     * @throws \Doctrine\DBAL\DBALException
     */
    public function countAll(){
        $em = $this->getEntityManager();
        $sql = "SELECT COUNT(*) as number FROM moniteur";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll()[0]['number'];
    }

    public function getMoniteursDipo($dateChosieSTR,$nombreHeures){
        $dateDebut = new \DateTime($dateChosieSTR);
        $dateFin = new \DateTime($dateChosieSTR);
        $dateFin->add(new \DateInterval('PT'.$nombreHeures.'H'));
        $em = $this->getEntityManager();
        $sql = "SELECT m.id FROM moniteur m INNER JOIN entrainement e ON m.id = e.moniteur WHERE
                (
                (e.dateDebut<=\"".date_format($dateDebut,"Y-m-d H:i:s")."\" AND e.dateFin>=\"".date_format($dateDebut,"Y-m-d H:i:s")."\") 
                    OR 
                (e.dateDebut<=\"".date_format($dateFin,"Y-m-d H:i:s")."\" AND e.dateFin>=\"".date_format($dateFin,"Y-m-d H:i:s")."\")
                )";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        $moniteurNonDiponible = $stmt->fetchAll(PDO::FETCH_COLUMN);
        $arr_as_string = implode( ',', $moniteurNonDiponible );
        if($moniteurNonDiponible!=null)
            $sql="SELECT id, nom, prenom FROM moniteur WHERE id NOT IN (".$arr_as_string.")";
        else {
            $sql="SELECT id, nom, prenom FROM moniteur";
        }
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
