<?php

namespace autoEcoleBundle\Repository;
use autoEcoleBundle\Entity\Voiture;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return integer
     * @throws \Doctrine\DBAL\DBALException
     */
    public function countAll(){
        $em = $this->getEntityManager();
        $sql = "SELECT COUNT(*) as number FROM voiture";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll()[0]['number'];
}
    public function getMarques(){
        $em = $this->getEntityManager();
        $sql = "SELECT DISTINCT marque FROM voiture";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }
    public function getModelesByMarque($marque){
        $em = $this->getEntityManager();
        $sql = "SELECT modele FROM voiture WHERE marque LIKE '".$marque."'";
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }

    /**
     * @param $voiture_id
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getEntrainementByVoiture($voiture_id){
        $em = $this->getEntityManager();
        $sql = "SELECT `dateDebut`,`dateFin` FROM entrainement WHERE voiture = ".$voiture_id;
        try {
            $stmt = $em->getConnection()->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
